// Code generated by protoc-gen-go. DO NOT EDIT.
// source: JWT-service.proto

package proto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type JWTToken struct {
	User                 string   `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	Token                string   `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *JWTToken) Reset()         { *m = JWTToken{} }
func (m *JWTToken) String() string { return proto.CompactTextString(m) }
func (*JWTToken) ProtoMessage()    {}
func (*JWTToken) Descriptor() ([]byte, []int) {
	return fileDescriptor_a3c35e2764b09a8c, []int{0}
}

func (m *JWTToken) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JWTToken.Unmarshal(m, b)
}
func (m *JWTToken) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JWTToken.Marshal(b, m, deterministic)
}
func (m *JWTToken) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JWTToken.Merge(m, src)
}
func (m *JWTToken) XXX_Size() int {
	return xxx_messageInfo_JWTToken.Size(m)
}
func (m *JWTToken) XXX_DiscardUnknown() {
	xxx_messageInfo_JWTToken.DiscardUnknown(m)
}

var xxx_messageInfo_JWTToken proto.InternalMessageInfo

func (m *JWTToken) GetUser() string {
	if m != nil {
		return m.User
	}
	return ""
}

func (m *JWTToken) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type JWTRequest struct {
	V1                   int64    `protobuf:"varint,1,opt,name=v1,proto3" json:"v1,omitempty"`
	User                 string   `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *JWTRequest) Reset()         { *m = JWTRequest{} }
func (m *JWTRequest) String() string { return proto.CompactTextString(m) }
func (*JWTRequest) ProtoMessage()    {}
func (*JWTRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a3c35e2764b09a8c, []int{1}
}

func (m *JWTRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JWTRequest.Unmarshal(m, b)
}
func (m *JWTRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JWTRequest.Marshal(b, m, deterministic)
}
func (m *JWTRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JWTRequest.Merge(m, src)
}
func (m *JWTRequest) XXX_Size() int {
	return xxx_messageInfo_JWTRequest.Size(m)
}
func (m *JWTRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_JWTRequest.DiscardUnknown(m)
}

var xxx_messageInfo_JWTRequest proto.InternalMessageInfo

func (m *JWTRequest) GetV1() int64 {
	if m != nil {
		return m.V1
	}
	return 0
}

func (m *JWTRequest) GetUser() string {
	if m != nil {
		return m.User
	}
	return ""
}

type JWTResponse struct {
	V1                   int64     `protobuf:"varint,1,opt,name=v1,proto3" json:"v1,omitempty"`
	JWTToken             *JWTToken `protobuf:"bytes,2,opt,name=JWTToken,proto3" json:"JWTToken,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *JWTResponse) Reset()         { *m = JWTResponse{} }
func (m *JWTResponse) String() string { return proto.CompactTextString(m) }
func (*JWTResponse) ProtoMessage()    {}
func (*JWTResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a3c35e2764b09a8c, []int{2}
}

func (m *JWTResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JWTResponse.Unmarshal(m, b)
}
func (m *JWTResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JWTResponse.Marshal(b, m, deterministic)
}
func (m *JWTResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JWTResponse.Merge(m, src)
}
func (m *JWTResponse) XXX_Size() int {
	return xxx_messageInfo_JWTResponse.Size(m)
}
func (m *JWTResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_JWTResponse.DiscardUnknown(m)
}

var xxx_messageInfo_JWTResponse proto.InternalMessageInfo

func (m *JWTResponse) GetV1() int64 {
	if m != nil {
		return m.V1
	}
	return 0
}

func (m *JWTResponse) GetJWTToken() *JWTToken {
	if m != nil {
		return m.JWTToken
	}
	return nil
}

type JWTRenewRequest struct {
	V1                   int64    `protobuf:"varint,1,opt,name=v1,proto3" json:"v1,omitempty"`
	JwtToken             string   `protobuf:"bytes,2,opt,name=jwtToken,proto3" json:"jwtToken,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *JWTRenewRequest) Reset()         { *m = JWTRenewRequest{} }
func (m *JWTRenewRequest) String() string { return proto.CompactTextString(m) }
func (*JWTRenewRequest) ProtoMessage()    {}
func (*JWTRenewRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a3c35e2764b09a8c, []int{3}
}

func (m *JWTRenewRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JWTRenewRequest.Unmarshal(m, b)
}
func (m *JWTRenewRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JWTRenewRequest.Marshal(b, m, deterministic)
}
func (m *JWTRenewRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JWTRenewRequest.Merge(m, src)
}
func (m *JWTRenewRequest) XXX_Size() int {
	return xxx_messageInfo_JWTRenewRequest.Size(m)
}
func (m *JWTRenewRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_JWTRenewRequest.DiscardUnknown(m)
}

var xxx_messageInfo_JWTRenewRequest proto.InternalMessageInfo

func (m *JWTRenewRequest) GetV1() int64 {
	if m != nil {
		return m.V1
	}
	return 0
}

func (m *JWTRenewRequest) GetJwtToken() string {
	if m != nil {
		return m.JwtToken
	}
	return ""
}

type JWTRenewResponse struct {
	V1                   int64     `protobuf:"varint,1,opt,name=v1,proto3" json:"v1,omitempty"`
	JWTToken             *JWTToken `protobuf:"bytes,2,opt,name=JWTToken,proto3" json:"JWTToken,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *JWTRenewResponse) Reset()         { *m = JWTRenewResponse{} }
func (m *JWTRenewResponse) String() string { return proto.CompactTextString(m) }
func (*JWTRenewResponse) ProtoMessage()    {}
func (*JWTRenewResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a3c35e2764b09a8c, []int{4}
}

func (m *JWTRenewResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JWTRenewResponse.Unmarshal(m, b)
}
func (m *JWTRenewResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JWTRenewResponse.Marshal(b, m, deterministic)
}
func (m *JWTRenewResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JWTRenewResponse.Merge(m, src)
}
func (m *JWTRenewResponse) XXX_Size() int {
	return xxx_messageInfo_JWTRenewResponse.Size(m)
}
func (m *JWTRenewResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_JWTRenewResponse.DiscardUnknown(m)
}

var xxx_messageInfo_JWTRenewResponse proto.InternalMessageInfo

func (m *JWTRenewResponse) GetV1() int64 {
	if m != nil {
		return m.V1
	}
	return 0
}

func (m *JWTRenewResponse) GetJWTToken() *JWTToken {
	if m != nil {
		return m.JWTToken
	}
	return nil
}

type JWTVerifyRequest struct {
	V1                   int64    `protobuf:"varint,1,opt,name=v1,proto3" json:"v1,omitempty"`
	JwtToken             string   `protobuf:"bytes,2,opt,name=jwtToken,proto3" json:"jwtToken,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *JWTVerifyRequest) Reset()         { *m = JWTVerifyRequest{} }
func (m *JWTVerifyRequest) String() string { return proto.CompactTextString(m) }
func (*JWTVerifyRequest) ProtoMessage()    {}
func (*JWTVerifyRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a3c35e2764b09a8c, []int{5}
}

func (m *JWTVerifyRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JWTVerifyRequest.Unmarshal(m, b)
}
func (m *JWTVerifyRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JWTVerifyRequest.Marshal(b, m, deterministic)
}
func (m *JWTVerifyRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JWTVerifyRequest.Merge(m, src)
}
func (m *JWTVerifyRequest) XXX_Size() int {
	return xxx_messageInfo_JWTVerifyRequest.Size(m)
}
func (m *JWTVerifyRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_JWTVerifyRequest.DiscardUnknown(m)
}

var xxx_messageInfo_JWTVerifyRequest proto.InternalMessageInfo

func (m *JWTVerifyRequest) GetV1() int64 {
	if m != nil {
		return m.V1
	}
	return 0
}

func (m *JWTVerifyRequest) GetJwtToken() string {
	if m != nil {
		return m.JwtToken
	}
	return ""
}

type JWTVerifyResponse struct {
	V1                   int64    `protobuf:"varint,1,opt,name=v1,proto3" json:"v1,omitempty"`
	Status               string   `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *JWTVerifyResponse) Reset()         { *m = JWTVerifyResponse{} }
func (m *JWTVerifyResponse) String() string { return proto.CompactTextString(m) }
func (*JWTVerifyResponse) ProtoMessage()    {}
func (*JWTVerifyResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a3c35e2764b09a8c, []int{6}
}

func (m *JWTVerifyResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JWTVerifyResponse.Unmarshal(m, b)
}
func (m *JWTVerifyResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JWTVerifyResponse.Marshal(b, m, deterministic)
}
func (m *JWTVerifyResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JWTVerifyResponse.Merge(m, src)
}
func (m *JWTVerifyResponse) XXX_Size() int {
	return xxx_messageInfo_JWTVerifyResponse.Size(m)
}
func (m *JWTVerifyResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_JWTVerifyResponse.DiscardUnknown(m)
}

var xxx_messageInfo_JWTVerifyResponse proto.InternalMessageInfo

func (m *JWTVerifyResponse) GetV1() int64 {
	if m != nil {
		return m.V1
	}
	return 0
}

func (m *JWTVerifyResponse) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func init() {
	proto.RegisterType((*JWTToken)(nil), "proto.JWTToken")
	proto.RegisterType((*JWTRequest)(nil), "proto.JWTRequest")
	proto.RegisterType((*JWTResponse)(nil), "proto.JWTResponse")
	proto.RegisterType((*JWTRenewRequest)(nil), "proto.JWTRenewRequest")
	proto.RegisterType((*JWTRenewResponse)(nil), "proto.JWTRenewResponse")
	proto.RegisterType((*JWTVerifyRequest)(nil), "proto.JWTVerifyRequest")
	proto.RegisterType((*JWTVerifyResponse)(nil), "proto.JWTVerifyResponse")
}

func init() { proto.RegisterFile("JWT-service.proto", fileDescriptor_a3c35e2764b09a8c) }

var fileDescriptor_a3c35e2764b09a8c = []byte{
	// 339 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x91, 0xc1, 0x4e, 0xc2, 0x40,
	0x10, 0x86, 0xd3, 0x2a, 0x0d, 0x0e, 0x51, 0x64, 0xa3, 0x48, 0x1a, 0x0f, 0x64, 0x4f, 0x06, 0x23,
	0x15, 0xf4, 0x84, 0xd1, 0x8b, 0x27, 0x7b, 0x31, 0xa9, 0x55, 0x0e, 0x9e, 0xaa, 0x8e, 0xa4, 0x68,
	0x76, 0xeb, 0xee, 0x02, 0x31, 0xc6, 0x8b, 0xaf, 0xe0, 0xab, 0xf8, 0x26, 0xbe, 0x82, 0x0f, 0x62,
	0x98, 0x16, 0xda, 0x84, 0x70, 0x31, 0x9e, 0xda, 0x99, 0x9d, 0xef, 0xef, 0xd7, 0x1d, 0xa8, 0xf9,
	0xfd, 0xf0, 0x40, 0xa3, 0x1a, 0xc7, 0xf7, 0xd8, 0x4e, 0x94, 0x34, 0x92, 0x95, 0xe8, 0xe1, 0xee,
	0x0e, 0xa4, 0x1c, 0x3c, 0xa3, 0x17, 0x25, 0xb1, 0x17, 0x09, 0x21, 0x4d, 0x64, 0x62, 0x29, 0x74,
	0x3a, 0xc4, 0x8f, 0xa1, 0xec, 0xf7, 0xc3, 0x50, 0x3e, 0xa1, 0x60, 0x0c, 0x56, 0x47, 0x1a, 0x55,
	0xc3, 0x6a, 0x5a, 0x7b, 0x6b, 0x01, 0xbd, 0xb3, 0x2d, 0x28, 0x99, 0xe9, 0x61, 0xc3, 0xa6, 0x66,
	0x5a, 0xf0, 0x43, 0x00, 0xbf, 0x1f, 0x06, 0xf8, 0x32, 0x42, 0x6d, 0xd8, 0x06, 0xd8, 0xe3, 0x0e,
	0x51, 0x2b, 0x81, 0x3d, 0xee, 0xcc, 0x73, 0xec, 0x3c, 0x87, 0xfb, 0x50, 0x21, 0x42, 0x27, 0x52,
	0x68, 0x5c, 0x40, 0xf6, 0x73, 0x0d, 0xc2, 0x2a, 0xdd, 0x6a, 0x2a, 0xd8, 0x9e, 0xb5, 0x83, 0xf9,
	0x00, 0x3f, 0x85, 0x2a, 0x65, 0x09, 0x9c, 0x2c, 0x53, 0x70, 0xa1, 0x3c, 0x9c, 0x98, 0xb0, 0x60,
	0x3e, 0xaf, 0xf9, 0x25, 0x6c, 0xe6, 0xf8, 0x7f, 0xf8, 0x9c, 0x51, 0xe0, 0x0d, 0xaa, 0xf8, 0xf1,
	0xf5, 0x2f, 0x42, 0x27, 0xb4, 0xbd, 0x19, 0xbf, 0xc4, 0xa8, 0x0e, 0x8e, 0x36, 0x91, 0x19, 0xe9,
	0x0c, 0xcf, 0xaa, 0xee, 0x97, 0x45, 0xbb, 0xb8, 0x4a, 0x57, 0xcf, 0x2e, 0xc0, 0x39, 0x57, 0x18,
	0x19, 0x64, 0xb5, 0x5c, 0x38, 0x93, 0x72, 0x59, 0xb1, 0x95, 0x7e, 0x87, 0x37, 0x3e, 0xbe, 0x7f,
	0x3e, 0x6d, 0xc6, 0xd7, 0xbd, 0xe1, 0xc4, 0x78, 0x03, 0x14, 0xa8, 0x22, 0x83, 0x3d, 0xab, 0xc5,
	0x6e, 0xc1, 0xb9, 0x4e, 0x1e, 0xa6, 0x51, 0xf5, 0x22, 0x97, 0xdf, 0xba, 0xbb, 0xb3, 0xd0, 0xcf,
	0x42, 0x9b, 0x14, 0xea, 0xba, 0xdb, 0x14, 0xaa, 0xa6, 0x67, 0xde, 0xdb, 0xec, 0x7f, 0xdf, 0x7b,
	0x56, 0xeb, 0xce, 0x21, 0xf2, 0xe8, 0x37, 0x00, 0x00, 0xff, 0xff, 0x7f, 0x52, 0x27, 0x7c, 0xb8,
	0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// JWTServiceClient is the client API for JWTService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type JWTServiceClient interface {
	Create(ctx context.Context, in *JWTRequest, opts ...grpc.CallOption) (*JWTResponse, error)
	Update(ctx context.Context, in *JWTRenewRequest, opts ...grpc.CallOption) (*JWTRenewResponse, error)
}

type jWTServiceClient struct {
	cc *grpc.ClientConn
}

func NewJWTServiceClient(cc *grpc.ClientConn) JWTServiceClient {
	return &jWTServiceClient{cc}
}

func (c *jWTServiceClient) Create(ctx context.Context, in *JWTRequest, opts ...grpc.CallOption) (*JWTResponse, error) {
	out := new(JWTResponse)
	err := c.cc.Invoke(ctx, "/proto.JWTService/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *jWTServiceClient) Update(ctx context.Context, in *JWTRenewRequest, opts ...grpc.CallOption) (*JWTRenewResponse, error) {
	out := new(JWTRenewResponse)
	err := c.cc.Invoke(ctx, "/proto.JWTService/Update", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// JWTServiceServer is the server API for JWTService service.
type JWTServiceServer interface {
	Create(context.Context, *JWTRequest) (*JWTResponse, error)
	Update(context.Context, *JWTRenewRequest) (*JWTRenewResponse, error)
}

// UnimplementedJWTServiceServer can be embedded to have forward compatible implementations.
type UnimplementedJWTServiceServer struct {
}

func (*UnimplementedJWTServiceServer) Create(ctx context.Context, req *JWTRequest) (*JWTResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (*UnimplementedJWTServiceServer) Update(ctx context.Context, req *JWTRenewRequest) (*JWTRenewResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Update not implemented")
}

func RegisterJWTServiceServer(s *grpc.Server, srv JWTServiceServer) {
	s.RegisterService(&_JWTService_serviceDesc, srv)
}

func _JWTService_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(JWTRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JWTServiceServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.JWTService/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JWTServiceServer).Create(ctx, req.(*JWTRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _JWTService_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(JWTRenewRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JWTServiceServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.JWTService/Update",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JWTServiceServer).Update(ctx, req.(*JWTRenewRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _JWTService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.JWTService",
	HandlerType: (*JWTServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _JWTService_Create_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _JWTService_Update_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "JWT-service.proto",
}
