// Code generated by protoc-gen-go. DO NOT EDIT.
// source: EventStore-service.proto

package proto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type EventStore struct {
	Uuid                 string   `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Event                string   `protobuf:"bytes,2,opt,name=event,proto3" json:"event,omitempty"`
	Command              string   `protobuf:"bytes,3,opt,name=command,proto3" json:"command,omitempty"`
	Data                 string   `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EventStore) Reset()         { *m = EventStore{} }
func (m *EventStore) String() string { return proto.CompactTextString(m) }
func (*EventStore) ProtoMessage()    {}
func (*EventStore) Descriptor() ([]byte, []int) {
	return fileDescriptor_d72370542f5b09a5, []int{0}
}

func (m *EventStore) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EventStore.Unmarshal(m, b)
}
func (m *EventStore) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EventStore.Marshal(b, m, deterministic)
}
func (m *EventStore) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EventStore.Merge(m, src)
}
func (m *EventStore) XXX_Size() int {
	return xxx_messageInfo_EventStore.Size(m)
}
func (m *EventStore) XXX_DiscardUnknown() {
	xxx_messageInfo_EventStore.DiscardUnknown(m)
}

var xxx_messageInfo_EventStore proto.InternalMessageInfo

func (m *EventStore) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *EventStore) GetEvent() string {
	if m != nil {
		return m.Event
	}
	return ""
}

func (m *EventStore) GetCommand() string {
	if m != nil {
		return m.Command
	}
	return ""
}

func (m *EventStore) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

type ReadAllRequest struct {
	V1                   int64    `protobuf:"varint,1,opt,name=v1,proto3" json:"v1,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReadAllRequest) Reset()         { *m = ReadAllRequest{} }
func (m *ReadAllRequest) String() string { return proto.CompactTextString(m) }
func (*ReadAllRequest) ProtoMessage()    {}
func (*ReadAllRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d72370542f5b09a5, []int{1}
}

func (m *ReadAllRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadAllRequest.Unmarshal(m, b)
}
func (m *ReadAllRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadAllRequest.Marshal(b, m, deterministic)
}
func (m *ReadAllRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadAllRequest.Merge(m, src)
}
func (m *ReadAllRequest) XXX_Size() int {
	return xxx_messageInfo_ReadAllRequest.Size(m)
}
func (m *ReadAllRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadAllRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ReadAllRequest proto.InternalMessageInfo

func (m *ReadAllRequest) GetV1() int64 {
	if m != nil {
		return m.V1
	}
	return 0
}

type ReadAllResponse struct {
	V1                   int64         `protobuf:"varint,1,opt,name=v1,proto3" json:"v1,omitempty"`
	EventStores          []*EventStore `protobuf:"bytes,2,rep,name=eventStores,proto3" json:"eventStores,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *ReadAllResponse) Reset()         { *m = ReadAllResponse{} }
func (m *ReadAllResponse) String() string { return proto.CompactTextString(m) }
func (*ReadAllResponse) ProtoMessage()    {}
func (*ReadAllResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d72370542f5b09a5, []int{2}
}

func (m *ReadAllResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadAllResponse.Unmarshal(m, b)
}
func (m *ReadAllResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadAllResponse.Marshal(b, m, deterministic)
}
func (m *ReadAllResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadAllResponse.Merge(m, src)
}
func (m *ReadAllResponse) XXX_Size() int {
	return xxx_messageInfo_ReadAllResponse.Size(m)
}
func (m *ReadAllResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadAllResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ReadAllResponse proto.InternalMessageInfo

func (m *ReadAllResponse) GetV1() int64 {
	if m != nil {
		return m.V1
	}
	return 0
}

func (m *ReadAllResponse) GetEventStores() []*EventStore {
	if m != nil {
		return m.EventStores
	}
	return nil
}

type ReadRequest struct {
	V1                   int64    `protobuf:"varint,1,opt,name=v1,proto3" json:"v1,omitempty"`
	Uuid                 string   `protobuf:"bytes,2,opt,name=uuid,proto3" json:"uuid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReadRequest) Reset()         { *m = ReadRequest{} }
func (m *ReadRequest) String() string { return proto.CompactTextString(m) }
func (*ReadRequest) ProtoMessage()    {}
func (*ReadRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d72370542f5b09a5, []int{3}
}

func (m *ReadRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadRequest.Unmarshal(m, b)
}
func (m *ReadRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadRequest.Marshal(b, m, deterministic)
}
func (m *ReadRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadRequest.Merge(m, src)
}
func (m *ReadRequest) XXX_Size() int {
	return xxx_messageInfo_ReadRequest.Size(m)
}
func (m *ReadRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ReadRequest proto.InternalMessageInfo

func (m *ReadRequest) GetV1() int64 {
	if m != nil {
		return m.V1
	}
	return 0
}

func (m *ReadRequest) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

type ReadResponse struct {
	V1                   int64       `protobuf:"varint,1,opt,name=v1,proto3" json:"v1,omitempty"`
	EventStore           *EventStore `protobuf:"bytes,2,opt,name=eventStore,proto3" json:"eventStore,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *ReadResponse) Reset()         { *m = ReadResponse{} }
func (m *ReadResponse) String() string { return proto.CompactTextString(m) }
func (*ReadResponse) ProtoMessage()    {}
func (*ReadResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d72370542f5b09a5, []int{4}
}

func (m *ReadResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadResponse.Unmarshal(m, b)
}
func (m *ReadResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadResponse.Marshal(b, m, deterministic)
}
func (m *ReadResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadResponse.Merge(m, src)
}
func (m *ReadResponse) XXX_Size() int {
	return xxx_messageInfo_ReadResponse.Size(m)
}
func (m *ReadResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ReadResponse proto.InternalMessageInfo

func (m *ReadResponse) GetV1() int64 {
	if m != nil {
		return m.V1
	}
	return 0
}

func (m *ReadResponse) GetEventStore() *EventStore {
	if m != nil {
		return m.EventStore
	}
	return nil
}

func init() {
	proto.RegisterType((*EventStore)(nil), "proto.EventStore")
	proto.RegisterType((*ReadAllRequest)(nil), "proto.ReadAllRequest")
	proto.RegisterType((*ReadAllResponse)(nil), "proto.ReadAllResponse")
	proto.RegisterType((*ReadRequest)(nil), "proto.ReadRequest")
	proto.RegisterType((*ReadResponse)(nil), "proto.ReadResponse")
}

func init() { proto.RegisterFile("EventStore-service.proto", fileDescriptor_d72370542f5b09a5) }

var fileDescriptor_d72370542f5b09a5 = []byte{
	// 319 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x91, 0x4d, 0x6e, 0xc2, 0x30,
	0x10, 0x46, 0x85, 0x81, 0x22, 0x06, 0x04, 0x62, 0xfa, 0x23, 0x0b, 0x75, 0x81, 0xbc, 0x62, 0x53,
	0xa2, 0xc0, 0x09, 0xaa, 0xaa, 0x8b, 0x2e, 0x1b, 0xa4, 0xee, 0x5d, 0x32, 0x42, 0x91, 0x82, 0x4d,
	0xb1, 0xc9, 0xa6, 0xea, 0xa6, 0x57, 0xe8, 0x11, 0x7a, 0xa4, 0x5e, 0xa1, 0x07, 0xa9, 0x6c, 0x03,
	0x09, 0xa8, 0xac, 0x62, 0x4f, 0xde, 0xbc, 0x99, 0x2f, 0x01, 0xfe, 0x58, 0x90, 0xb2, 0x73, 0xab,
	0x37, 0x74, 0x67, 0x68, 0x53, 0x64, 0x0b, 0x9a, 0xac, 0x37, 0xda, 0x6a, 0x6c, 0xfa, 0xc7, 0xf0,
	0x76, 0xa9, 0xf5, 0x32, 0xa7, 0x48, 0xae, 0xb3, 0x48, 0x2a, 0xa5, 0xad, 0xb4, 0x99, 0x56, 0x26,
	0x40, 0x22, 0x05, 0x28, 0x05, 0x88, 0xd0, 0xd8, 0x6e, 0xb3, 0x94, 0xd7, 0x46, 0xb5, 0x71, 0x3b,
	0xf1, 0x67, 0xbc, 0x82, 0x26, 0x39, 0x82, 0x33, 0x5f, 0x0c, 0x17, 0xe4, 0xd0, 0x5a, 0xe8, 0xd5,
	0x4a, 0xaa, 0x94, 0xd7, 0x7d, 0x7d, 0x7f, 0x75, 0x8e, 0x54, 0x5a, 0xc9, 0x1b, 0xc1, 0xe1, 0xce,
	0x62, 0x04, 0xbd, 0x84, 0x64, 0x7a, 0x9f, 0xe7, 0x09, 0xbd, 0x6d, 0xc9, 0x58, 0xec, 0x01, 0x2b,
	0x62, 0x3f, 0xa7, 0x9e, 0xb0, 0x22, 0x16, 0x2f, 0xd0, 0x3f, 0x10, 0x66, 0xad, 0x95, 0xa1, 0x53,
	0x04, 0x67, 0xd0, 0xa1, 0xc3, 0xaa, 0x86, 0xb3, 0x51, 0x7d, 0xdc, 0x99, 0x0e, 0x42, 0x8e, 0x49,
	0x19, 0x22, 0xa9, 0x52, 0x22, 0x86, 0x8e, 0xf3, 0x9e, 0x19, 0x7b, 0x08, 0xcc, 0xca, 0xc0, 0xe2,
	0x19, 0xba, 0xa1, 0xe5, 0xcc, 0x1e, 0x31, 0x40, 0x39, 0xc1, 0x77, 0xfe, 0xbb, 0x46, 0x05, 0x9a,
	0x7e, 0xd7, 0x60, 0x50, 0xbe, 0x9a, 0x87, 0xdf, 0x84, 0x4f, 0xd0, 0xda, 0x65, 0xc6, 0xeb, 0x5d,
	0xff, 0xf1, 0x57, 0x1a, 0xde, 0x9c, 0x96, 0xc3, 0x4a, 0xa2, 0xff, 0xf9, 0xf3, 0xfb, 0xc5, 0xda,
	0xd8, 0x8a, 0xc8, 0x44, 0x32, 0xcf, 0xf1, 0x01, 0x1a, 0x8e, 0x41, 0xac, 0x34, 0xec, 0x25, 0x97,
	0x47, 0xb5, 0x9d, 0x01, 0xbd, 0xa1, 0x8b, 0xe0, 0x0c, 0xef, 0x2e, 0xf7, 0xc7, 0xeb, 0x85, 0xe7,
	0x66, 0x7f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x46, 0x65, 0xea, 0x58, 0x53, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// EventStoreServiceClient is the client API for EventStoreService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type EventStoreServiceClient interface {
	ReadAll(ctx context.Context, in *ReadAllRequest, opts ...grpc.CallOption) (*ReadAllResponse, error)
	Read(ctx context.Context, in *ReadRequest, opts ...grpc.CallOption) (*ReadResponse, error)
}

type eventStoreServiceClient struct {
	cc *grpc.ClientConn
}

func NewEventStoreServiceClient(cc *grpc.ClientConn) EventStoreServiceClient {
	return &eventStoreServiceClient{cc}
}

func (c *eventStoreServiceClient) ReadAll(ctx context.Context, in *ReadAllRequest, opts ...grpc.CallOption) (*ReadAllResponse, error) {
	out := new(ReadAllResponse)
	err := c.cc.Invoke(ctx, "/proto.EventStoreService/ReadAll", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eventStoreServiceClient) Read(ctx context.Context, in *ReadRequest, opts ...grpc.CallOption) (*ReadResponse, error) {
	out := new(ReadResponse)
	err := c.cc.Invoke(ctx, "/proto.EventStoreService/Read", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EventStoreServiceServer is the server API for EventStoreService service.
type EventStoreServiceServer interface {
	ReadAll(context.Context, *ReadAllRequest) (*ReadAllResponse, error)
	Read(context.Context, *ReadRequest) (*ReadResponse, error)
}

// UnimplementedEventStoreServiceServer can be embedded to have forward compatible implementations.
type UnimplementedEventStoreServiceServer struct {
}

func (*UnimplementedEventStoreServiceServer) ReadAll(ctx context.Context, req *ReadAllRequest) (*ReadAllResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReadAll not implemented")
}
func (*UnimplementedEventStoreServiceServer) Read(ctx context.Context, req *ReadRequest) (*ReadResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Read not implemented")
}

func RegisterEventStoreServiceServer(s *grpc.Server, srv EventStoreServiceServer) {
	s.RegisterService(&_EventStoreService_serviceDesc, srv)
}

func _EventStoreService_ReadAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadAllRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventStoreServiceServer).ReadAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.EventStoreService/ReadAll",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventStoreServiceServer).ReadAll(ctx, req.(*ReadAllRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EventStoreService_Read_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventStoreServiceServer).Read(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.EventStoreService/Read",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventStoreServiceServer).Read(ctx, req.(*ReadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _EventStoreService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.EventStoreService",
	HandlerType: (*EventStoreServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ReadAll",
			Handler:    _EventStoreService_ReadAll_Handler,
		},
		{
			MethodName: "Read",
			Handler:    _EventStoreService_Read_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "EventStore-service.proto",
}
